# Generated by Django 4.2 on 2023-04-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('department', 'name', 'surname', 'patronymic')},
        ),
    ]
