# Generated by Django 4.2 on 2023-04-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230409_0059'),
    ]

    operations = [
        migrations.RemoveField('Employee', 'full_name'),
    ]
